name: Deploy NestJS to AWS Beanstalk (AWS CLI Version)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Створюємо архів. Включаємо dist, package.json, package-lock.json Procfile
      - name: Generate deployment package
        run: zip -r deploy.zip dist package.json package-lock.json Procfile

      # Авторизація в AWS
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 1. Завантажуємо архів у S3
      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://aws-nestjs-actions-bucket/deploy-${{ github.sha }}.zip

      # 2. Реєструємо нову версію застосунку в Beanstalk
      - name: Create Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "aws-nestjs-actions-app" \
            --version-label "ver-${{ github.sha }}" \
            --source-bundle S3Bucket="aws-nestjs-actions-bucket",S3Key="deploy-${{ github.sha }}.zip"

      # 3. Оновлюємо середовище на нову версію
      - name: Update Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name "aws-nestjs-actions-env" \
            --version-label "ver-${{ github.sha }}"
