name: Deploy NestJS to AWS EB
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install & Build
        run: |
          npm ci
          npm run build
          
      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x "node_modules/*" "src/*" "*.git*" # Пакуємо без вихідного коду та модулів

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to EB
        uses: aws-actions/aws-elasticbeanstalk-deploy@v2 # Використання офіційної дії
        with:
          application_name: MyNestApp
          environment_name: MyNestApp-env
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deploy.zip
